#!/usr/bin/env bash
# install.sh - One-command installer for Phantom Board
# Generated by easy-install-generator (github.com/KyleBuildsAI)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/KyleBuildsAI/phantom-board/main/install.sh | bash
#   - or -
#   bash install.sh
#
set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────────────────

PROJECT="Phantom Board"
VERSION="0.1.0"
DESCRIPTION="Visual AI agent orchestration dashboard"
REPO_URL="https://github.com/KyleBuildsAI/phantom-board"
RUNTIME="docker"

# ─── Colors & Symbols ──────────────────────────────────────────────────────────

if [ -t 1 ] && command -v tput >/dev/null 2>&1; then
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RESET=$(tput sgr0)
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    CYAN=$(tput setaf 6)
else
    BOLD="" DIM="" RESET="" RED="" GREEN="" YELLOW="" BLUE="" CYAN=""
fi

CHECK="${GREEN}✓${RESET}"
CROSS="${RED}✗${RESET}"
ARROW="${CYAN}→${RESET}"

# ─── Helper Functions ───────────────────────────────────────────────────────────

print_header() {
    echo ""
    echo "  ${BOLD}${BLUE}╔══════════════════════════════════════════════╗${RESET}"
    printf "  ${BOLD}${BLUE}║${RESET}  %-42s  ${BOLD}${BLUE}║${RESET}\n" "${BOLD}${PROJECT}${RESET}  v${VERSION}"
    printf "  ${BOLD}${BLUE}║${RESET}  ${DIM}%-42s${RESET}  ${BOLD}${BLUE}║${RESET}\n" "${DESCRIPTION}"
    echo "  ${BOLD}${BLUE}╚══════════════════════════════════════════════╝${RESET}"
    echo ""
}

print_success() {
    echo ""
    echo "  ${BOLD}${GREEN}╔══════════════════════════════════════════════╗${RESET}"
    printf "  ${BOLD}${GREEN}║${RESET}  ${CHECK} %-40s  ${BOLD}${GREEN}║${RESET}\n" "${BOLD}Installation Complete!${RESET}"
    echo "  ${BOLD}${GREEN}╚══════════════════════════════════════════════╝${RESET}"
    echo ""
}

step() {
    local num="$1" total="$2" msg="$3"
    printf "  ${BOLD}[%d/%d]${RESET} %-28s" "$num" "$total" "$msg"
}

ok() {
    echo "${CHECK} $*"
}

fail() {
    echo "${CROSS} $*"
}

warn() {
    echo "  ${YELLOW}⚠${RESET}  $*"
}

info() {
    echo "  ${ARROW} $*"
}

die() {
    echo ""
    echo "  ${RED}${BOLD}Error:${RESET} $*"
    echo ""
    exit 1
}

# ─── Determine Install Directory ────────────────────────────────────────────────

# If run via curl pipe, clone the repo first
if [ ! -f "install.sh" ] && [ ! -f "requirements.txt" ] && [ ! -f "package.json" ] && [ ! -f "docker-compose.yml" ]; then
    print_header
    info "Downloading ${PROJECT}..."
    echo ""

    if command -v git >/dev/null 2>&1; then
        git clone --depth 1 "${REPO_URL}.git" "${PROJECT}" 2>/dev/null || \
            die "Failed to clone repository. Check your internet connection."
        cd "${PROJECT}"
    else
        # Fallback to zip download
        TMPZIP=$(mktemp /tmp/${PROJECT}-XXXXXX.zip)
        if command -v curl >/dev/null 2>&1; then
            curl -fsSL "${REPO_URL}/archive/refs/heads/main.zip" -o "$TMPZIP" || \
                die "Failed to download. Check your internet connection."
        elif command -v wget >/dev/null 2>&1; then
            wget -q "${REPO_URL}/archive/refs/heads/main.zip" -O "$TMPZIP" || \
                die "Failed to download. Check your internet connection."
        else
            die "Need git, curl, or wget to download the project."
        fi
        unzip -q "$TMPZIP" -d /tmp/${PROJECT}-tmp 2>/dev/null || die "Failed to extract archive."
        mv /tmp/${PROJECT}-tmp/*/ "./${PROJECT}" 2>/dev/null || mv /tmp/${PROJECT}-tmp/* "./${PROJECT}"
        rm -f "$TMPZIP" && rm -rf /tmp/${PROJECT}-tmp
        cd "${PROJECT}"
    fi
else
    print_header
fi

INSTALL_DIR="$(pwd)"

# ═══════════════════════════════════════════════════════════════════════════════
# Docker Install Flow
# ═══════════════════════════════════════════════════════════════════════════════

TOTAL_STEPS=4

# Step 1: Check Docker
step 1 $TOTAL_STEPS "Checking Docker..."
if ! command -v docker >/dev/null 2>&1; then
    fail "Docker not found"
    echo ""
    warn "Install Docker first:"
    info "macOS:  brew install --cask docker"
    info "Linux:  curl -fsSL https://get.docker.com | sh"
    info "Docs:   https://docs.docker.com/get-docker/"
    die "Docker is required to run ${PROJECT}."
fi
DOCKER_VER=$(docker --version | grep -oE '[0-9]+\.[0-9]+' | head -1)
ok "Docker ${DOCKER_VER}"

# Step 2: Check Docker Compose
step 2 $TOTAL_STEPS "Checking Compose..."
if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
    COMPOSE_VER=$(docker compose version --short 2>/dev/null || echo "v2+")
    ok "Docker Compose ${COMPOSE_VER}"
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
    COMPOSE_VER=$(docker-compose version --short 2>/dev/null || echo "v1")
    ok "docker-compose ${COMPOSE_VER}"
else
    fail "Docker Compose not found"
    die "Docker Compose is required. Update Docker Desktop or install the compose plugin."
fi

# Step 3: Configure environment
step 3 $TOTAL_STEPS "Configuring..."
if [ -f ".env.example" ] && [ ! -f ".env" ]; then
    cp .env.example .env
    ok "Created .env from template"
    echo ""
    info "Review .env and adjust settings if needed."
elif [ -f ".env" ]; then
    ok ".env already exists"
else
    ok "No configuration needed"
fi

# Step 4: Start services
step 4 $TOTAL_STEPS "Starting services..."
$COMPOSE_CMD up -d 2>/dev/null || die "Failed to start services."
ok "All services running"

print_success

echo "  Get started:"
echo "    ${ARROW} Open ${BOLD}http://localhost:3000${RESET} in your browser"
echo "    ${ARROW} $COMPOSE_CMD logs -f       ${DIM}# View logs${RESET}"
echo "    ${ARROW} $COMPOSE_CMD down          ${DIM}# Stop${RESET}"
echo ""
echo "  Docs: ${BOLD}${REPO_URL}${RESET}"
echo ""

